---
language: go
services:
  - docker

env:
  global:
    - GOOGLE_CLOUD_KEYFILE_JSON=~/dev-gcp.json
    - GOOGLE_CREDENTIALS=~/dev-gcp.json

cache:
  directories:
    - ${HOME}/.terraform
    - ${HOME/terraform.tfstate.d

before_install:
  - echo $BASE64_GOOGLE_CREDENTIALS | base64 --decode -i > ${HOME}/dev-gcp.json
  - curl -sLo ${HOME}/terraform.zip https://releases.hashicorp.com/terraform/0.12.21/terraform_0.12.21_linux_amd64.zip
  - unzip ${HOME}/terraform.zip
  - export PATH="$(pwd):$PATH"

stages:
  - init
  - plan
  - apply

jobs:
  include:
    - stage: init
      script:
        - ls -la
        - terraform init

    - stage: plan
      script:
        - echo $(pwd)
        - ls -la
        - terraform workspace new dev
        - terraform plan -out "planfile"
      dependencies:
        - init
      artifacts:
        paths:
          - planfile

    - stage: apply
      script:
        - terraform apply -input=false "planfile"
      dependencies:
        - plan
      # when: manual
