---
language: go
services:
  - docker

env:
  global:
    - GOOGLE_CLOUD_KEYFILE_JSON=~/dev-gcp.json
    - GOOGLE_CREDENTIALS=~/dev-gcp.json

before_install:
  - echo $BASE64_GOOGLE_CREDENTIALS | base64 --decode -i > ${HOME}/dev-gcp.json
  - docker pull hashicorp/terraform:light

stages:
  - validate
  - init
  - plan
  - apply


jobs:
  include:
    - stage: validate
      script:
        - docker container run --rm hashicorp/terraform:light validate

    - stage: init
      script:
        - docker container run -it -v ${PWD}:${PWD}/terraform -w ${PWD}/terraform hashicorp/terraform:light init
      artifacts:
        paths:
          - .terraform

    - stage: plan
      script:
        - docker container run -it -v ${PWD}:${PWD}/terraform -w ${PWD}/terraform hashicorp/terraform:light workspace new dev
        - docker container run -it -v ${PWD}:${PWD}/terraform -w ${PWD}/terraform hashicorp/terraform:light plan -out "planfile"
      dependencies:
        - validate
      artifacts:
        paths:
          - planfile

    - stage: apply
      script:
        - docker container run -it hashicorp/terraform:light apply -input=false "planfile"
      dependencies:
        - plan
      # when: manual
