---
language: go
services:
  - docker

env:
  global:
    - GOOGLE_CLOUD_KEYFILE_JSON=~/dev-gcp.json
    - GOOGLE_CREDENTIALS=~/dev-gcp.json

cache:
  directories:
    - .terraform
    - terraform.tfstate.d

before_install:
  - echo $BASE64_GOOGLE_CREDENTIALS | base64 --decode -i > ${HOME}/dev-gcp.json
  - docker pull hashicorp/terraform:light

stages:
  - validate
  - init
  - plan
  - apply


jobs:
  include:
    - stage: validate
      script:
        - docker container run --rm hashicorp/terraform:light validate

    - stage: init
      script:
        - docker container run -it -v ${PWD}:${PWD}/terraform -w ${PWD}/terraform hashicorp/terraform:light init
        - echo ${pwd}
        - ls -la
      dependencies:
          - validate
      artifacts:
        paths:
          - .terraform
          - terraform.tfstate.d

    - stage: plan
      script:
        - docker container run -it -v ${PWD}:${PWD}/terraform -w ${PWD}/terraform hashicorp/terraform:light workspace new dev
        - docker container run -it -v ${PWD}:${PWD}/terraform -w ${PWD}/terraform hashicorp/terraform:light plan -out "planfile"
      dependencies:
        - init
      artifacts:
        paths:
          - planfile

    - stage: apply
      script:
        - docker container run -it -v ${PWD}:${PWD}/terraform -w ${PWD}/terraform hashicorp/terraform:light apply -input=false "planfile"
      dependencies:
        - plan
      # when: manual
