---
language: go
services:
  - docker

before_install:
  - docker pull hashicorp/terraform:light

stages:
  - validate
  - init
  - plan
  - apply


jobs:
  include:
    - stage: validate
      script:
        - docker container run --rm hashicorp/terraform:light validate

    - stage: init
      script:
        - docker container run --rm hashicorp/terraform:light init

    - stage: plan
      script:
        - docker container run -it hashicorp/terraform:light new dev
        - docker container run -it hashicorp/terraform:light select dev
        - docker container run -it hashicorp/terraform:light plan -out "planfile"
      dependencies:
        - validate
      artifacts:
        paths:
          - planfile

    - stage: apply
      script:
        - docker container run -it hashicorp/terraform:light apply -input=false "planfile"
      dependencies:
        - plan
      when: manual
