---
language: go
services:
  - docker

before_install:
  - docker pull hashicorp/terraform:light

stages:
  - tf
  - validate
  - plan
  - apply


jobs:
  include:
    - stage: tf
      script:
        - hashicorp/terraform:light --version
        - hashicorp/terraform:light init

    - stage: validate
      script:
        - hashicorp/terraform:light validate

    - stage: plan
      script:
        - hashicorp/terraform:light plan -out "planfile"
      dependencies:
        - validate
      artifacts:
        paths:
          - planfile

    - stage: apply
      script:
        - hashicorp/terraform:light apply -input=false "planfile"
      dependencies:
        - plan
      when: manual
